# Site settings
title: Green Five
email: GreenFiveGame@writeme.com
description: > # this means to ignore newlines until "baseurl:"
  This is the development blog for GreenFive, a story based FPS/RPG in the vein of SystemShock.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
github_username:  JoeWode

# Build settings
markdown: kramdown
